### PR TITLE
use  zmq.green  instead of gevent_zmq

### PR DESCRIPTION
**Pull request by nom3ad**
now pyzmq has  built in support for gevent. so  zmq.green module can be used  instead of gevent_zmq compatibility layer.

### CODE REVIEW

**Comment by bombela** [comment]
zerorpc has some workaround in its zmq green support. They might not be necessary anymore though. If I ever get some time, I will look into it.

**Comment by earonesty** [comment]
this fixes some bugs too.

**Comment by nom3ad** [comment]
@earonesty   if you could elaborate on those bugs, that would be helpful.  I've been using this library in production for a while.

**Comment by nom3ad** [comment]
@bombela
I've been vendoring  zerorpc-python with this patch for like 3 years in production.  But It would be nice to use it from upstream.   
Just poking, in case you lost track of this. :slightly_smiling_face:

**Comment by brifordwylie** [comment]
@bombela can you peek at this PR when you get a chance :)

**Comment by bheadmaster** [comment]
Is this repository still maintained?
It would be sad to see such a great project fade out.

**Comment by bombela** [comment]
Yes still maintained. I am mostly concerned by bug fixes.

**Pull request closed without merging**
