### PR TITLE
Fix type of msg ids, should be string

### PR DESCRIPTION
**Pull request by eruvanos**

### CODE REVIEW

**Comment by eruvanos** [comment]
Hi,
using ZeroRPC with the [Golang](https://github.com/bsphere/zerorpc) server, results in an error for the Response OK event.

It looks like the go server is sending the requests properly, but the channels on Pythons client side are stored as binary. Which makes the request fail.

Link
[Get channel](https://github.com/0rpc/zerorpc-python/blob/c8b2f644b24088ea385d8c0f4663cf231c33fbc1/zerorpc/channel.py#L86)

It looks like this is easy to fix using converting the msg id while creation time.

**Comment by bombela** [comment]
The msgpack type of the message ID is a `Binary`, not `String`. This is the intended behavior.

It suspect the Go side is not handling the distinction properly. Assuming the code is not handling the type explicitly, my guess would be that somebody decided to defaults to the `String` type.

See https://github.com/msgpack/msgpack/blob/master/spec.md#str-format-family

**Comment by eruvanos** [comment]
Ok thanks for your feedback, one short question,
I just tested it with Python 2 and it works, is it an ok that it works with Python 2 but not 3?

**Comment by eruvanos** [comment]
I was able to fix the issue, thank you very much for the hint to the type system.

**Comment by bombela** [comment]
Thanks for the detailed reporting. Glad you got the issue sorted out.

The header keys are unicode strings utf8 encoded (that is, a bytestring interpreted as a utf8 encoded unicode string!). The message IDs are bytestrings.

But we can see here that the nodejs implementation doesn't respect that and instead encodes ID as unicode strings. The python2/3 is all good as we can see in your example. You got confused by the printed representation of unicode and byte strings between python2 and python3.

python | bytestring | unicode string
-- | -- | --
python 2 | "foo" | u"bar"
python 3 | b"foo" | "bar"

**Pull request closed without merging**
