### PR TITLE
Python 3 support

### PR DESCRIPTION
**Pull request by mylokin**
Added python 3.5 support, dropped python 3.1, 3.2 support.
Based on beta version of gevent 1.1
related ticket #108

### CODE REVIEW

**Comment by mylokin** [comment]
seems like gevent 1.1b5 crushes accidentally

**Comment by bombela** [comment]
Nice work. I will merge into some branch (whenever I get on my laptop) before we can feel confident that the impact on pytbon 2.7 is minimal.

**Comment by drennalls** [comment]
FWIW I tried the patch using gevent 1.1b6 on a CentOS 7.1 box under Python 3.4 and the tests ran ok... I applied like this...
```
git clone https://github.com/0rpc/zerorpc-python.git
cd zerorpc-python
wget https://patch-diff.githubusercontent.com/raw/0rpc/zerorpc-python/pull/129.patch
patch -p1 < 129.patch
..adjusted the gevent requirement in setup.py from the patch..
 requirements = [
-    'gevent>=1.0',
+    'gevent==1.1b6'
```
..and ran tests like this..
```
(VENV34) [root@here zerorpc-python]# python -V
Python 3.4.3

(VENV34) [root@here zerorpc-python]# ZPC_TEST_TIME_FACTOR=0.2 nosetests -v
...snip...
----------------------------------------------------------------------
Ran 79 tests in 28.522s

OK
```

**Comment by thedrow** [comment]
Gevent is already at RC1 :)

**Comment by drennalls** [comment]
@thedrow 
Yes it is :).. as of Nov 14th... I tried things over a week ago before that release was out.

**Comment by ramnes** [comment]
Hey @bombela,

Do you think you could find some time to take a look at that PR? I really would like to try out 0rpc on a production project, but the lack of Python 3 support prevents me to.

Bisous à mon astek préféré ! :heart:

**Comment by bombela** [comment]
@ramnes  Ahah c'est demandé si gentillement :3

I can't promise anything, but I will do my best to look into by next week. I will create a branch for it, and setup the unit tests.

**Comment by ramnes** [comment]
Awesome. I don't know the code base at all, but don't hesitate to ask if there's anything I can do.

**Comment by bombela** [comment]
see branch python3.4.

(and sorry @mylokin for not using your work, I figured I had to go trough every single line of code anyway, and I wanted to make sure everything works on python 2.6, 2.7 and 3.4).

**Pull request closed without merging**
